-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-dynamicconfig/db/mwstake_dynamic_config.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mwstake_dynamic_config (
  mwdc_key BLOB NOT NULL, mwdc_serialized BLOB DEFAULT NULL,
  mwdc_timestamp BLOB DEFAULT NULL,
  mwdc_is_active SMALLINT DEFAULT 1 NOT NULL
);
