-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: components/mwstake-mediawiki-component-dynamicconfig/db/mwstake_dynamic_config_serialized_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__mwstake_dynamic_config AS
SELECT
  mwdc_key,
  mwdc_serialized,
  mwdc_timestamp,
  mwdc_is_active
FROM /*_*/mwstake_dynamic_config;
DROP TABLE /*_*/mwstake_dynamic_config;


CREATE TABLE /*_*/mwstake_dynamic_config (
    mwdc_key BLOB NOT NULL, mwdc_serialized BLOB DEFAULT NULL,
    mwdc_timestamp BLOB DEFAULT NULL,
    mwdc_is_active SMALLINT DEFAULT 1 NOT NULL
  );
INSERT INTO /*_*/mwstake_dynamic_config (
    mwdc_key, mwdc_serialized, mwdc_timestamp,
    mwdc_is_active
  )
SELECT
  mwdc_key,
  mwdc_serialized,
  mwdc_timestamp,
  mwdc_is_active
FROM
  /*_*/__temp__mwstake_dynamic_config;
DROP TABLE /*_*/__temp__mwstake_dynamic_config;
