-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: components/mwstake-mediawiki-component-dynamicconfig/db/mwstake_dynamic_config_serialized_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/mwstake_dynamic_config
  CHANGE mwdc_serialized mwdc_serialized LONGBLOB DEFAULT NULL;
