-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: components/mwstake-mediawiki-component-dynamicconfig/db/mwstake_dynamic_config.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mwstake_dynamic_config (
  mwdc_key VARBINARY(255) NOT NULL,
  mwdc_serialized LONGBLOB DEFAULT NULL,
  mwdc_timestamp BINARY(14) DEFAULT NULL,
  mwdc_is_active TINYINT(1) DEFAULT 1 NOT NULL
) /*$wgDBTableOptions*/;
